### ISSUE TITLE
Allow Users to Edit their Contact Info

### ISSUE THREAD

**Issue by p6knewman** [linkedin/oncall#114]
I currently use user_sync.py via ldap_sync.py to pull down all users' contact information from LDAP, but many users either do not want their full contact info published in LDAP or want different contact info used for Oncall. This leaves us with a "hybrid" source of user attributes. 

I've been using [oncall-admin]( https://github.com/dwang159/oncall-admin) as a stopgap to edit user contact info that differs from LDAP, but are there any plans/features underway to integrate the same functionality into the user's respective Settings page?

I would be happy to write such functionality into Oncall if I have your support for the feature.

**Comment by wleese** [comment]
This is a problem we're also facing.
In our chat solution, users are able to change their own 'mention' name, which is used for notifying users. This information is not stored in LDAP.

**Comment by houqp** [comment]
Before we start brainstorming on how to support merging user info from multiple sources, I would suggest you think about whether this is really the route you want to go after.

Is it possible to push back and enforce everyone to edit their info from a single source? Because that would save you and users lots of headache down the road. Even at Linkedin where all the info is managed in a single source (LDAP), we are still getting frequent internal support tickets asking where to change their number. I can imagine it will get much worse if you have multiple sources to manage.

Now, if you REALLY want multi source support, I think the easier way is to build a custom user sync script where you merge the info from multiple sources before shipping to oncall db. The sync script itself is pretty simple and static so it should be easy to maintain.

**Comment by wleese** [comment]
> I would suggest you think about whether this is really the route you want to go after.

We've given this quite some thought and ended up wanting this feature. 

Three reasons:
- When people lose their phone outside of workhours (meaning no one is available to make the change in LDAP).
- When people want to use their private phonenumber to receive alerts, but do not want to expose it company wide.
- When people change their user name in whatever chat solution is used. This is possible in Hipchat*

( * granted, this reason is highly specific. )

This could be implemented outside of oncall (in the sync script or through using oncall-admin), but I'm pretty sure this feature would be something one would expect of oncall.

**Comment by wleese** [comment]
@p6knewman I believe this can be closed now.

**Comment by Peak6DevOps** [comment]
🤜

**Comment by p6knewman** [comment]
🤜
