### ISSUE TITLE
error while creating new team

### ISSUE THREAD

**Issue by afsalkr** [linkedin/oncall#78]
i am facing 404 error while creating a new team from oncall interface. Also, i could see that so many options are not available on the interface.

![oncall error](https://user-images.githubusercontent.com/30264151/28319960-f23a3dae-6bec-11e7-86a6-cc983be46f97.PNG)

**Comment by dwang159** [comment]
What is the request that 404s? Is your API set up correctly? Do you see errors in the logs?
Also, I'm not sure what you mean that "options are not available on the interface". What options are you looking for?

**Comment by afsalkr** [comment]
Thanks for your reply. I have installed the oncall application using the following docker commands.

docker run --name oncall-mysql -e MYSQL_ROOT_PASSWORD='1234' -d mysql
docker pull quay.io/iris/oncall
docker run -d --link oncall-mysql:mysql -p 8080:8080 -e DOCKER_DB_BOOTSTRAP=1 quay.io/iris/oncall

Do i need to do any other configuration for API?

**Comment by dwang159** [comment]
Have you tried installing the dev environment and running `make serve` instead? What happens then?

**Comment by yalvinz** [comment]
stupid

**Comment by NocturnalShadow** [comment]
Hello, guys. I'm having exactly the same issue. Deployed oncall in cloud using the provided Helm chart. 
I can edit the test team just fine. But when trying to create a new one get this 404. Same happens when using API.

Interestingly enough, when I provide some invalid data, (e.g. slack channel without # at the beginning) I actually see 400 with the corresponding errors listed here: https://github.com/linkedin/oncall/blob/master/src/oncall/api/v0/teams.py#L150 (and below), so I assume the request handling method actually works but fails somewhere further...

Would appreciate your help.

Using "debug" auth module (tried both, debug disabled and enabled) if that's relevant.
