### ISSUE TITLE
home page to not show teams/schedules without logging in

### ISSUE THREAD

**Issue by logix88** [linkedin/oncall#81]
It seems you can browse all teams data right on the home page even before you can login... this should be restricted so it's only show post-login.

**Comment by joedissmeyer** [comment]
@logix88 I'm definitely going to +1 this one. 

I know this tool is designed so that it is an "internal-only" app and is for a select subset of people (i.e. IT people only). However I know that once certain members of our business learn the URL for the tool they'll abuse it and start reaching out directly to people, bypassing the service desk. Plus, having a person's name and phone number viewable without any authentication up front will be a flag for our IT security team.

**Comment by jeremybender-work** [comment]
I'm running into the same issue;  otherwise the app looks like an excellent fit for our needs.   Perhaps a good balance would be keeping the name/schedule public, but requiring a login to see contact details.

**Comment by diegocepedaw** [comment]
This issue was addressed in [https://github.com/linkedin/oncall/pull/181](url) Setting force_login_splash to true in the config.yaml file will require a login to view the app's content.
